### PR TITLE
Googlepicker

### PR DESCRIPTION
**Pull request by ticruz38**
can you give it a try on your machine, it works for me...

---
This change is [Reviewable](https://reviewable.io/reviews/gorgias/gorgias-chrome/171)

### CODE REVIEW

**Comment by xarg** [comment]
Seems that when I open the extension for the first time it asks me to authenticate with Google - that is annoying, not sure what is causing it. Even after logging in it opens another Google Login window even though I just logged in.

The user should be only asked to login to google if the click on the Upload button - never before.

---

Review status: 0 of 11 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/gorgias/gorgias-chrome/171#-:-KDNROh6HNPtroaGv7xx:-2061248150)*

**Comment by ticruz38** [comment]
Yeah, ok, I will try smthg this  afternoon, it's quite awful to debug that feature since you have to refresh browser cache everytime, is the file picker working though?

**Comment by xarg** [comment]
Filepicker not working for me.

On Mon, Mar 21, 2016 at 12:27 PM, Ticruz <notifications@github.com> wrote:

> Yeah, ok, I will try smthg this afternoon, it's quite awful to debug that
> feature since you have to refresh browser cache everytime, is the file
> picker working though?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/gorgias/gorgias-chrome/pull/171#issuecomment-199233084>
>



-- 
Alex Plugaru
Write e-mails faster with Gorgias (Techstars '15)
https://gorgias.io/

**Comment by ticruz38** [comment]
here is a first glance on file attachment in gmail, though gmail seems to attach some javascript on their file attachment node.
I still have to handle the proper image for pdf, jpeg, png etc...
And write some script to have the exact same behaviour as 'native' gmail webapp.

**Comment by xarg** [comment]
So I pushed the changes for in the manifest it would work with our master google account. Check the changes here: https://github.com/gorgias/gorgias-chrome/tree/googlepicker


It appears however that when I insert the template the file gets removed after the email was sent. I'm gonna work on the sync part. Can you please download the above branch and try to see if it works for you?

---

Reviewed 2 of 11 files at r1, 1 of 3 files at r2, 6 of 10 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/gorgias/gorgias-chrome/171#-:-KFpT9Ejp3WCqm-9oAuk:626481385)*

**Comment by ticruz38** [comment]
the google filepicker is working properly, the google drive has somehow disappeared in your commit.. I will put it back.
I tried sending a mail to myself with files attached, it all work as expected... I have the file attached to my mail either in sent mailbox and received mailbox. I still have the same template with files attached after sending my mail. I can't figure out the bug you report.
where are the files removed from? the template? the maibox?

**Comment by xarg** [comment]
This was merged in 5.1.0

**Pull request closed without merging**
