### PR TITLE
Add Filter by Tag

### PR DESCRIPTION
**Pull request by MiiNoe879**
This change is [Reviewable](https://reviewable.io/reviews/gorgias/gorgias-chrome/264)

### CODE REVIEW

**Comment by xarg** [comment]
Fuzzy/substring searching is not enough because the string of the tag could be quite common. Please implement the syntax filter specified in the issue description: #264

**Comment by xarg** [comment]
Again, please read carefully the issue. Note the syntax: 

`in: sales <Search String>`

This means you match all templates that have the exact match of `sales` tag and then you search the string <Search string> in the templates that match that tag. Basically, it's an AND operator between them.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

*[src/common/helpers.js, line 101 at r2](https://beta.reviewable.io/reviews/gorgias/gorgias-chrome/264#-L7W-d1V8HLSAAfII3hZ:-L7W-d1V8HLSAAfII3h_:bz6ipoo) ([raw file](https://github.com/gorgias/gorgias-chrome/blob/72f0cf92b2690c9d63ec4a52254b5cf5f40c1a89/src/common/helpers.js#L101)):*
> ```JavaScript
>     if (opts.threshold === 0) {
>         if(text.startsWith('in:')) {
>             if (i.tags && i.tags.indexOf(text) !== -1) {
> ```

this is going to match substrings in tags and not exact matches. It should only match exact matches of tags nothing more.

---

*[src/common/helpers.js, line 120 at r2](https://beta.reviewable.io/reviews/gorgias/gorgias-chrome/264#-L7W-lHuDe-YE6YSGrgv:-L7W-lHuDe-YE6YSGrgw:bu144dd) ([raw file](https://github.com/gorgias/gorgias-chrome/blob/72f0cf92b2690c9d63ec4a52254b5cf5f40c1a89/src/common/helpers.js#L120)):*
> ```JavaScript
> 
>     if(text.startsWith('in:')) {
>         var defaultOptions = {
> ```

why duplicate this part of code? put this variable above this scope and reuse it in the IF and ELSE>

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/gorgias/gorgias-chrome/264#-:-L7W07b79muduGRdUAnn:b43xpw8)*

**Comment by xarg** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/gorgias/gorgias-chrome/264)*

**Comment by xarg** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[src/common/helpers.js, line 120 at r2](https://reviewable.io:443/reviews/gorgias/gorgias-chrome/264#-L7W-lHuDe-YE6YSGrgv:-L7_tvSRTtlpxzSJ7cSM:b8p614b) ([raw file](https://github.com/gorgias/gorgias-chrome/blob/72f0cf92b2690c9d63ec4a52254b5cf5f40c1a89/src/common/helpers.js#L120)):*
<details><summary><i>Previously, xarg (Alex Plugaru) wrote…</i></summary><blockquote>

why duplicate this part of code? put this variable above this scope and reuse it in the IF and ELSE>
</blockquote></details>

Please mark my comments with `Done` when you're done with an issue.

---

*[src/common/helpers.js, line 93 at r3](https://reviewable.io:443/reviews/gorgias/gorgias-chrome/264#-L7_t7Y37AgXsZfLYnYp:-L7_t7Y37AgXsZfLYnYq:b-z6cw1i) ([raw file](https://github.com/gorgias/gorgias-chrome/blob/5524e681cffd2366ffa595dc4035fb1addc78999/src/common/helpers.js#L93)):*
> ```JavaScript
> };
> 
> var filterByTagSearchText = function(list, text, threshold) {
> ```

can you please add a few comments about what are you doing in these functions? it's pretty hard to read.

---

*[src/common/helpers.js, line 102 at r3](https://reviewable.io:443/reviews/gorgias/gorgias-chrome/264#-L7_tXAHIHxGOjihFBJx:-L7_tXAHIHxGOjihFBJy:bb5yxn3) ([raw file](https://github.com/gorgias/gorgias-chrome/blob/5524e681cffd2366ffa595dc4035fb1addc78999/src/common/helpers.js#L102)):*
> ```JavaScript
>             tag = searchParts[0].trim();
>             for(var i=1; i<searchParts.length; i++)
>                 searchStr += searchParts[i].trim()+' ';
> ```

please follow eslint

---

*[src/common/helpers.js, line 110 at r3](https://reviewable.io:443/reviews/gorgias/gorgias-chrome/264#-L7_tBH54jyiWisdVocV:-L7_tBH54jyiWisdVocW:b-wk2xej) ([raw file](https://github.com/gorgias/gorgias-chrome/blob/5524e681cffd2366ffa595dc4035fb1addc78999/src/common/helpers.js#L110)):*
> ```JavaScript
>     }
> }
> var filter = function(list, tag, searchStr, threshold) {
> ```

can you name this function to something less generic? Similar to what do you did with filterByTagSearchText?

---

*[src/common/helpers.js, line 117 at r3](https://reviewable.io:443/reviews/gorgias/gorgias-chrome/264#-L7_tLYaDC1pEDIu6kX5:-L7_tLYaDC1pEDIu6kX6:b-314qt1) ([raw file](https://github.com/gorgias/gorgias-chrome/blob/5524e681cffd2366ffa595dc4035fb1addc78999/src/common/helpers.js#L117)):*
> ```JavaScript
>             var tags = item.tags;
>             tags = tags.split(',');
>             
> ```

please use an editor that does not leave these trailing spaces and follows the `.editorconfig` file (in the root of the project).

---

*[src/common/helpers.js, line 127 at r3](https://reviewable.io:443/reviews/gorgias/gorgias-chrome/264#-L7_tQaCm32P1vnnUW1r:-L7_tQaCm32P1vnnUW1s:b-hss400) ([raw file](https://github.com/gorgias/gorgias-chrome/blob/5524e681cffd2366ffa595dc4035fb1addc78999/src/common/helpers.js#L127)):*
> ```JavaScript
>             var body = item.body.toLowerCase();
>             if(threshold == 1) {
>                 return (item.tags.indexOf(tag) != -1) && ((shortcut && shortcut.indexOf(searchStr) != -1) || (title && title.indexOf(searchStr) != -1) || (body && body.indexOf(searchStr) != -1));
> ```

this not very readable, please split it into multile lines.

---

*[src/common/helpers.js, line 130 at r3](https://reviewable.io:443/reviews/gorgias/gorgias-chrome/264#-L7_tt3fB4vG6Piye_Hq:-L7_tt3fB4vG6Piye_Hr:bnj7hl0) ([raw file](https://github.com/gorgias/gorgias-chrome/blob/5524e681cffd2366ffa595dc4035fb1addc78999/src/common/helpers.js#L130)):*
> ```JavaScript
>             }
>             else {
>                 return (item.tags.indexOf(tag) != -1) && ((shortcut && (shortcut == searchStr)) || (title && (title == searchStr)) || (body && (body == searchStr)));
> ```

same as above

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gorgias/gorgias-chrome/264)*

**Comment by MiiNoe879** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[src/common/helpers.js, line 101 at r2](https://reviewable.io:443/reviews/gorgias/gorgias-chrome/264#-L7W-d1V8HLSAAfII3hZ:-L7a03TQuQbbrkni474h:b-896fix) ([raw file](https://github.com/gorgias/gorgias-chrome/blob/72f0cf92b2690c9d63ec4a52254b5cf5f40c1a89/src/common/helpers.js#L101)):*
<details><summary><i>Previously, xarg (Alex Plugaru) wrote…</i></summary><blockquote>

this is going to match substrings in tags and not exact matches. It should only match exact matches of tags nothing more.
</blockquote></details>

Done.

---

*[src/common/helpers.js, line 120 at r2](https://reviewable.io:443/reviews/gorgias/gorgias-chrome/264#-L7W-lHuDe-YE6YSGrgv:-L7a04B1GLMBX_GlQ9CL:b-896fix) ([raw file](https://github.com/gorgias/gorgias-chrome/blob/72f0cf92b2690c9d63ec4a52254b5cf5f40c1a89/src/common/helpers.js#L120)):*
<details><summary><i>Previously, xarg (Alex Plugaru) wrote…</i></summary><blockquote>

Please mark my comments with `Done` when you're done with an issue.
</blockquote></details>

Done.

---

*[src/common/helpers.js, line 93 at r3](https://reviewable.io:443/reviews/gorgias/gorgias-chrome/264#-L7_t7Y37AgXsZfLYnYp:-L7a-yRN2GsaeFU-wSoM:b-896fix) ([raw file](https://github.com/gorgias/gorgias-chrome/blob/5524e681cffd2366ffa595dc4035fb1addc78999/src/common/helpers.js#L93)):*
<details><summary><i>Previously, xarg (Alex Plugaru) wrote…</i></summary><blockquote>

can you please add a few comments about what are you doing in these functions? it's pretty hard to read.
</blockquote></details>

Done.

---

*[src/common/helpers.js, line 102 at r3](https://reviewable.io:443/reviews/gorgias/gorgias-chrome/264#-L7_tXAHIHxGOjihFBJx:-L7a0-dFWbjLBA_M63qe:b-896fix) ([raw file](https://github.com/gorgias/gorgias-chrome/blob/5524e681cffd2366ffa595dc4035fb1addc78999/src/common/helpers.js#L102)):*
<details><summary><i>Previously, xarg (Alex Plugaru) wrote…</i></summary><blockquote>

please follow eslint
</blockquote></details>

Done.

---

*[src/common/helpers.js, line 110 at r3](https://reviewable.io:443/reviews/gorgias/gorgias-chrome/264#-L7_tBH54jyiWisdVocV:-L7a00Msm_CT3w9iKSef:b-896fix) ([raw file](https://github.com/gorgias/gorgias-chrome/blob/5524e681cffd2366ffa595dc4035fb1addc78999/src/common/helpers.js#L110)):*
<details><summary><i>Previously, xarg (Alex Plugaru) wrote…</i></summary><blockquote>

can you name this function to something less generic? Similar to what do you did with filterByTagSearchText?
</blockquote></details>

Done.

---

*[src/common/helpers.js, line 117 at r3](https://reviewable.io:443/reviews/gorgias/gorgias-chrome/264#-L7_tLYaDC1pEDIu6kX5:-L7a00tYsC65oIZ7yo_s:b-896fix) ([raw file](https://github.com/gorgias/gorgias-chrome/blob/5524e681cffd2366ffa595dc4035fb1addc78999/src/common/helpers.js#L117)):*
<details><summary><i>Previously, xarg (Alex Plugaru) wrote…</i></summary><blockquote>

please use an editor that does not leave these trailing spaces and follows the `.editorconfig` file (in the root of the project).
</blockquote></details>

Done.

---

*[src/common/helpers.js, line 127 at r3](https://reviewable.io:443/reviews/gorgias/gorgias-chrome/264#-L7_tQaCm32P1vnnUW1r:-L7a01VwhqVa6Mm63v_D:b-896fix) ([raw file](https://github.com/gorgias/gorgias-chrome/blob/5524e681cffd2366ffa595dc4035fb1addc78999/src/common/helpers.js#L127)):*
<details><summary><i>Previously, xarg (Alex Plugaru) wrote…</i></summary><blockquote>

this not very readable, please split it into multile lines.
</blockquote></details>

Done.

---

*[src/common/helpers.js, line 130 at r3](https://reviewable.io:443/reviews/gorgias/gorgias-chrome/264#-L7_tt3fB4vG6Piye_Hq:-L7a02QFfPX7hJ6b9n1v:b-896fix) ([raw file](https://github.com/gorgias/gorgias-chrome/blob/5524e681cffd2366ffa595dc4035fb1addc78999/src/common/helpers.js#L130)):*
<details><summary><i>Previously, xarg (Alex Plugaru) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gorgias/gorgias-chrome/264)*

**Comment by xarg** [comment]
I think this could be done with a much simpler approach. Closing this for now.

**Pull request closed without merging**
