### PR TITLE
Amplitude

### PR DESCRIPTION
**Pull request by martinlatrille**
Branch from `ticruz38`'s fork

---
This change is [Reviewable](https://reviewable.io/reviews/gorgias/gorgias-chrome/197)

### CODE REVIEW

**Comment by martinlatrille** [comment]
List if events we need (just the basics): 
- [x] Installed Gorgias
- [x] Create template (private / shared; from extension page, from quick access button) 
- [x] Insert template (Property = source)
- [x] Delete template
- [x] Open settings
- [x] Open signup form
- [ ] Click signup on signup form
- [ ] Click yearly subscription

**Comment by xarg** [comment]
please grep logEvent and replace with getInstance().logEvent() also remove the bower components that are not related to this PR

<details><summary><i>Previously, martinlatrille (MartinLatrille) wrote…</i></summary>
> List if events we need (just the basics): 
> 
> - [x] Installed Gorgias
> 
> - [x] Create template (private / shared; from extension page, from quick access button) 
> 
> - [x] Insert template (Property = source)
> 
> - [x] Delete template
> 
> - [x] Open settings
> 
> - [x] Open signup form
> 
> - [ ] Click signup on signup form
> 
> - [ ] Click yearly subscription
> 
> 
> 
> Actually the two lasts should be set on `gorgias.io` since the modal in the extension is just an iframe.
</details>


---

Reviewed 10 of 40 files at r1, 10 of 21 files at r2, 1 of 1 files at r3.
Review status: 14 of 53 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/background/js/chrome-config.js, line 54 \[r3\]](https://reviewable.io:443/reviews/gorgias/gorgias-chrome/197#-KK8nPCl7yDsO0V28DyU:-KK8nPCl7yDsO0V28DyV:1442437094) ([raw file](https://github.com/gorgias/gorgias-chrome/blob/488005925011499e40fedc00048ee93e5cbacc67/src/background/js/chrome-config.js#L54)):*
> ```JavaScript
>     chrome.runtime.onInstalled.addListener(function (details) {
>         if (details.reason == "install") {
>             amplitude.logEvent("Installed Gorgias");
> ```

getInstance

---

*[src/background/js/environment.js, line 1 \[r3\]](https://reviewable.io:443/reviews/gorgias/gorgias-chrome/197#-KK8nRmjekUmmfcZwt8q:-KK8nRmjekUmmfcZwt8r:1760509663) ([raw file](https://github.com/gorgias/gorgias-chrome/blob/488005925011499e40fedc00048ee93e5cbacc67/src/background/js/environment.js#L1)):*
> ```JavaScript
> var ENV = "development";
> ```

dont commit this file

---

*[src/pages/bg.html, line 8 \[r3\]](https://reviewable.io:443/reviews/gorgias/gorgias-chrome/197#-KK8oUhKbtOkminn6AQP:-KK8oUhLA2QNm1DV0Lbo:1353622607) ([raw file](https://github.com/gorgias/gorgias-chrome/blob/488005925011499e40fedc00048ee93e5cbacc67/src/pages/bg.html#L8)):*
> ```HTML
>     <script src="../background/js/background.js"></script>
>     <script src="https://checkout.stripe.com/checkout.js"></script>
>     <script src="https://d24n15hnbwhuhn.cloudfront.net/libs/amplitude-2.11.0-min.gz.js"></script>
> ```

is this needed? isnt it loaded from the utils script?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gorgias/gorgias-chrome/197#-:-KK8ocO0BZvXYihvSswc:-1325303638)*

**Comment by martinlatrille** [comment]
Review status: 14 of 31 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/background/js/chrome-config.js, line 54 \[r3\]](https://reviewable.io:443/reviews/gorgias/gorgias-chrome/197#-KK8nPCl7yDsO0V28DyU:-KK8pHBaeFb2BAYgLt25:-499146009) ([raw file](https://github.com/gorgias/gorgias-chrome/blob/488005925011499e40fedc00048ee93e5cbacc67/src/background/js/chrome-config.js#L54)):*
<details><summary><i>Previously, xarg (Alex Plugaru) wrote…</i></summary>
> getInstance
</details>
Done.

---

*[src/background/js/environment.js, line 1 \[r3\]](https://reviewable.io:443/reviews/gorgias/gorgias-chrome/197#-KK8nRmjekUmmfcZwt8q:-KK8pgen9_6syXo5nBnP:-499146009) ([raw file](https://github.com/gorgias/gorgias-chrome/blob/488005925011499e40fedc00048ee93e5cbacc67/src/background/js/environment.js#L1)):*
<details><summary><i>Previously, xarg (Alex Plugaru) wrote…</i></summary>
> dont commit this file
</details>
Done.

---

*[src/pages/bg.html, line 8 \[r3\]](https://reviewable.io:443/reviews/gorgias/gorgias-chrome/197#-KK8oUhKbtOkminn6AQP:-KK8pfdzwrz3QonuOQzz:-499146009) ([raw file](https://github.com/gorgias/gorgias-chrome/blob/488005925011499e40fedc00048ee93e5cbacc67/src/pages/bg.html#L8)):*
<details><summary><i>Previously, xarg (Alex Plugaru) wrote…</i></summary>
> is this needed? isnt it loaded from the utils script?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gorgias/gorgias-chrome/197)*

**Comment by xarg** [comment]
Reviewed 10 of 21 files at r2, 7 of 7 files at r4, 3 of 25 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/gorgias/gorgias-chrome/197)*

**Pull request merged**
