### PR TITLE
Add an option for case sensitive search

### LINKED ISSUE #123: Add an option for case sensitive search
Add a parameter to have case sensitive search in the search dialog search box (and non case sensitive search where not enabled)

Should be disabled by default, so the search should be non case sensitive by default. Rationale: no search is case sensitive on Gorgias.io / gorgias-chrome

### PR DESCRIPTION
**Pull request by Yann-Pravo**
Add a _Enable Case Sensitive Search_ checkbox in _Auto-complete Dialog_ section in settings to enable case sensitive search in the dialog search box

Closes #123

---
This change is [Reviewable](https://reviewable.io/reviews/gorgias/gorgias-chrome/198)

### CODE REVIEW

**Comment by xarg** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/content/js/index.js, line 78 \[r1\]](https://reviewable.io:443/reviews/gorgias/gorgias-chrome/198#-KKrBRuBmkj1iZjhA5Tg:-KKrBRuBmkj1iZjhA5Th:-2121115509) ([raw file](https://github.com/gorgias/gorgias-chrome/blob/e2a485c50c07ccc3dcafb5a30fd4aa3b761648f2/src/content/js/index.js#L78)):*
> ```JavaScript
>                         if (text) {
>                             if (App.settings.case_sensitive_search) {
>                                 if (t.shortcut.toLowerCase().indexOf(text.toLowerCase()) !== -1 ||
> ```

could you make this part a bit more generic (a function)?

---

*[src/content/js/index.js, line 242 \[r1\]](https://reviewable.io:443/reviews/gorgias/gorgias-chrome/198#-KKrC2DnOF_qrtIOGap6:-KKrC2DnOF_qrtIOGap7:539211420) ([raw file](https://github.com/gorgias/gorgias-chrome/blob/e2a485c50c07ccc3dcafb5a30fd4aa3b761648f2/src/content/js/index.js#L242)):*
> ```JavaScript
>     // Check if we should use editor markup
>     App.settings.editor_enabled = settings.editor.enabled;
>     // Check if case sensitive search is enable
> ```

enabled

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gorgias/gorgias-chrome/198)*

**Comment by xarg** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/content/js/index.js, line 77 \[r2\]](https://reviewable.io:443/reviews/gorgias/gorgias-chrome/198#-KKsXqeiDVJHkS-qadW4:-KKsXqejb0TR52Koo-lm:442895520) ([raw file](https://github.com/gorgias/gorgias-chrome/blob/c16a040c3e85d0d3db3819f5c093b3bd6c59d6de/src/content/js/index.js#L77)):*
> ```JavaScript
>                         // we have some text, do the filtering
>                         if (text) {
>                             var templateRegex = new RegExp(text, App.settings.case_sensitive_search ? 'i' : '');
> ```

you should escape the text before using it in RegExp

---

*[src/pages/views/settings.html, line 51 \[r2\]](https://reviewable.io:443/reviews/gorgias/gorgias-chrome/198#-KKsY03vPInJeydFc8kt:-KKsY03vPInJeydFc8ku:-1127983606) ([raw file](https://github.com/gorgias/gorgias-chrome/blob/c16a040c3e85d0d3db3819f5c093b3bd6c59d6de/src/pages/views/settings.html#L51)):*
> ```HTML
>         <label for="caseSensitive">
>             <input type="checkbox" id="caseSensitive" ng-model="settings.qaBtn.caseSensitiveSearch" ng-change="updateSettings()"/>
>             Disable Case Sensitive Search
> ```

 Most of the settings use the word Enable so please use that as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gorgias/gorgias-chrome/198)*

**Comment by Yann-Pravo** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/content/js/index.js, line 78 \[r1\]](https://reviewable.io:443/reviews/gorgias/gorgias-chrome/198#-KKrBRuBmkj1iZjhA5Tg:-KKwlE-ntHKz8lBvJd20:-499146009) ([raw file](https://github.com/gorgias/gorgias-chrome/blob/e2a485c50c07ccc3dcafb5a30fd4aa3b761648f2/src/content/js/index.js#L78)):*
<details><summary><i>Previously, xarg (Alex Plugaru) wrote…</i></summary>
> could you make this part a bit more generic (a function)?
</details>
Done.

---

*[src/content/js/index.js, line 242 \[r1\]](https://reviewable.io:443/reviews/gorgias/gorgias-chrome/198#-KKrC2DnOF_qrtIOGap6:-KKwlF-JKMehXfVFVx1E:-499146009) ([raw file](https://github.com/gorgias/gorgias-chrome/blob/e2a485c50c07ccc3dcafb5a30fd4aa3b761648f2/src/content/js/index.js#L242)):*
<details><summary><i>Previously, xarg (Alex Plugaru) wrote…</i></summary>
> enabled
</details>
Done.

---

*[src/content/js/index.js, line 77 \[r2\]](https://reviewable.io:443/reviews/gorgias/gorgias-chrome/198#-KKsXqeiDVJHkS-qadW4:-KKwko47TCetCHMAhn7F:-1824670743) ([raw file](https://github.com/gorgias/gorgias-chrome/blob/c16a040c3e85d0d3db3819f5c093b3bd6c59d6de/src/content/js/index.js#L77)):*
<details><summary><i>Previously, xarg (Alex Plugaru) wrote…</i></summary>
> you should escape the text before using it in RegExp
</details>
Should I? The text variable is only read by de RegExp

---

*[src/pages/views/settings.html, line 51 \[r2\]](https://reviewable.io:443/reviews/gorgias/gorgias-chrome/198#-KKsY03vPInJeydFc8kt:-KKwlFyjjobBUkiVxEFM:2104666156) ([raw file](https://github.com/gorgias/gorgias-chrome/blob/c16a040c3e85d0d3db3819f5c093b3bd6c59d6de/src/pages/views/settings.html#L51)):*
<details><summary><i>Previously, xarg (Alex Plugaru) wrote…</i></summary>
>  Most of the settings use the word Enable so please use that as well.
</details>
I'll change the settings then because the option is to disable it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gorgias/gorgias-chrome/198)*

**Comment by xarg** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/common/storage.js, line 104 \[r3\]](https://reviewable.io:443/reviews/gorgias/gorgias-chrome/198#-KL0TCFOCYHSEbYbzQJM:-KL0TCFP7p96e3-awig1:266382806) ([raw file](https://github.com/gorgias/gorgias-chrome/blob/54ed1664ae4c61457afa5911859d2d553fe6675e/src/common/storage.js#L104)):*
> ```JavaScript
>                 enabled: true,
>                 shownPostInstall: false,
>                 caseSensitiveSearch: true
> ```

this should be false

---

*[src/content/js/index.js, line 77 \[r2\]](https://reviewable.io:443/reviews/gorgias/gorgias-chrome/198#-KKsXqeiDVJHkS-qadW4:-KL0SdZyWBTF57fdsBKz:-1769058502) ([raw file](https://github.com/gorgias/gorgias-chrome/blob/c16a040c3e85d0d3db3819f5c093b3bd6c59d6de/src/content/js/index.js#L77)):*
<details><summary><i>Previously, Yann-Pravo (Yann Pravo) wrote…</i></summary>
> Should I? The text variable is only read by de RegExp
</details>
if the user enters an invalid regex we'll get errors in our sentry for no reason. I think you should stick with indexOf (which is faster anyway).

---

*[src/content/js/index.js, line 17 \[r3\]](https://reviewable.io:443/reviews/gorgias/gorgias-chrome/198#-KL0TD_YQNegifdQ2SPq:-KL0TD_YQNegifdQ2SPr:-468164802) ([raw file](https://github.com/gorgias/gorgias-chrome/blob/54ed1664ae4c61457afa5911859d2d553fe6675e/src/content/js/index.js#L17)):*
> ```JavaScript
>     settings: {
>         suggestions_enabled: false,
>         case_sensitive_search: true,
> ```

false

---

*[src/pages/views/settings.html, line 51 \[r2\]](https://reviewable.io:443/reviews/gorgias/gorgias-chrome/198#-KKsY03vPInJeydFc8kt:-KL0T0_PNNEd7dxPKUkA:-1905422005) ([raw file](https://github.com/gorgias/gorgias-chrome/blob/c16a040c3e85d0d3db3819f5c093b3bd6c59d6de/src/pages/views/settings.html#L51)):*
<details><summary><i>Previously, Yann-Pravo (Yann Pravo) wrote…</i></summary>
> I'll change the settings then because the option is to disable it
</details>
Or you can leave it unchecked by default here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gorgias/gorgias-chrome/198)*

**Comment by Yann-Pravo** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/common/storage.js, line 104 \[r3\]](https://reviewable.io:443/reviews/gorgias/gorgias-chrome/198#-KL0TCFOCYHSEbYbzQJM:-KL0tct0jSlDOjYI1tYM:-1207601642) ([raw file](https://github.com/gorgias/gorgias-chrome/blob/54ed1664ae4c61457afa5911859d2d553fe6675e/src/common/storage.js#L104)):*
<details><summary><i>Previously, xarg (Alex Plugaru) wrote…</i></summary>
> this should be false
</details>
Oh yeah right, sorry. I was sure Romain said case sensitive enabled by default. I'll change that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gorgias/gorgias-chrome/198)*

**Comment by xarg** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/gorgias/gorgias-chrome/198)*

**Pull request merged**
