### PR TITLE
Design V3

### PR DESCRIPTION
**Pull request by martinlatrille**
## Design-v2 + Design-v3
This PR finishes the "Move gorgias.io to extension" GitHub issue.

[Review on Reviewable](https://reviewable.io/reviews/gorgias/gorgias-chrome/163)

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/gorgias/gorgias-chrome/pull/163" target="_blank">ReviewNinja

**Comment by xarg** [comment]
Initial comments:

- [ ] Select all label should be connected to the checkbox.
- [ ] Click 'Select all' -> Delete -> Cancel ==> Select all Checkbox is deselected.
- [ ] `&times;` not vertically centered: 
- [ ] helpdesk sub is still shown

---

Reviewed 3 of 35 files at r1, 33 of 58 files at r2.
Review status: 36 of 77 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/common/storage.js, line 90 \[r2\]](https://reviewable.io:443/reviews/gorgias/gorgias-chrome/163#-K8PqYN_U0er4k0QKk4x:-K8PqYN_U0er4k0QKk4y:189304829) ([raw file](https://github.com/gorgias/gorgias-chrome/blob/0e4bbfd90d62aa84cbc27a13a06db33a5749baa1/src/common/storage.js#L90)):*
These things should not get committed.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/gorgias/gorgias-chrome/163#-:-K8Pm4rWcpdwE1fZLJ_f:-2019746199)*

**Comment by martinlatrille** [comment]
### Select all label should be connected to the checkbox.

What do you mean ?

### helpdesk sub is still shown

The plans are sent through the API; I can make a filter client-side to squeeze the Helpdesk plans from the data received but it's a bit dirty. Considering we're probably going to split the Quicktexts API from the rest of Gorgias.io, I think we should remove the helpdesk plans from the API when we do that.

**Comment by xarg** [comment]
I mean when you click on the label ('select all' text) it doesn't activate the checkbox.
API of plans should be changed to allow a filter like: show only startup plans - use that filter in the extension side.

---

Review status: 36 of 77 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/gorgias/gorgias-chrome/163#-:-K8Qc1pPMR3us0sNJ0oa:-956958893)*

**Comment by xarg** [comment]
Reviewed 16 of 35 files at r1, 25 of 58 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/background/js/controllers/list.js, line 507 \[r2\]](https://reviewable.io:443/reviews/gorgias/gorgias-chrome/163#-K8Qr9WoQ9Shuml3ftPv:-K8Qr9WoQ9Shuml3ftPw:814273158) ([raw file](https://github.com/gorgias/gorgias-chrome/blob/0e4bbfd90d62aa84cbc27a13a06db33a5749baa1/src/background/js/controllers/list.js#L507)):*
This should be false only if  r === true

---

*[src/pages/includes/signup.html, line 8 \[r2\]](https://reviewable.io:443/reviews/gorgias/gorgias-chrome/163#-K8Qcw8qYCotLZywCJS8:-K8Qcw8qYCotLZywCJS9:933829602) ([raw file](https://github.com/gorgias/gorgias-chrome/blob/0e4bbfd90d62aa84cbc27a13a06db33a5749baa1/src/pages/includes/signup.html#L8)):*
Maybe have a param here?

---

*[src/pages/views/account/includes/delete_account_form.html, line 1 \[r2\]](https://reviewable.io:443/reviews/gorgias/gorgias-chrome/163#-K8Qd8DKqsZAY18A_Rrj:-K8Qd8DKqsZAY18A_Rrk:-1391124560) ([raw file](https://github.com/gorgias/gorgias-chrome/blob/0e4bbfd90d62aa84cbc27a13a06db33a5749baa1/src/pages/views/account/includes/delete_account_form.html#L1)):*
This file is not required. Please remove it.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/gorgias/gorgias-chrome/163)*

**Comment by xarg** [comment]
To fix/implement:

- [ ] Private/Shared templates
- [ ] Private/Share checkbox toggle when editing template.

---

Reviewed 7 of 8 files at r3, 18 of 22 files at r4, 13 of 13 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/gorgias/gorgias-chrome/163#-:-K8aDNgs_9R3i-CtKJ6Z:-961437583)*

**Comment by RomainLapeyre** [comment]
## Feedback on v3

- Scroll in signup popin: avoid and scroll the entire page, not only the popin (same as new template window)
- Template list: bug with the 2nd tag display, the tag and the text should be tighter
https://www.dropbox.com/s/mv6kt51sm813183/Screenshot%202016-01-21%2018.04.14.png?dl=0
- New Template + template list: tag font-size should be smaller? 
- Side bar, template menu: add a 10px margin-top & margin bottom for All, Shared & Private? 
- Login: if you install the extension, login, your templates are not automatically synced, you need to refresh 2 times for the templates which are on your account to populate

**Comment by martinlatrille** [comment]
- [ ] Unselect list link ("All", "Shared" or "Private") when a tag link is selected
- [ ] Change the behavior of the scroll in the signup modal
- [ ] Fix the 2nd tag display bug in the templates list
- [ ] Reduce tag font-size in the sidebar and the templates list
- [ ] Add a margin-top and margin-bottom to List Links (All, Private and Shared)
- [ ] Fix templates sync at login

**Comment by xarg** [comment]
Reviewed 1 of 8 files at r3, 6 of 16 files at r7, 9 of 15 files at r8, 10 of 10 files at r9, 5 of 5 files at r10.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/gorgias/gorgias-chrome/163)*

**Pull request closed without merging**
