### PR TITLE
Quick-access button

### PR DESCRIPTION
**Pull request by ghinda**
Implemented the quick-access button.
    
* The button will show up on the top-right of textareas, contenteditables, and `input[type=text]`.
* Clicking it opens the autocomplete dialog, positioned under it, similar to a dropdown.
* Added an option in the background settings page to be able to toggle it on and off.

It doesn't work in Gmail right now, because the required focus events are not triggered for some reason. I'll have to look into it some more.

### CODE REVIEW

**Comment by xarg** [comment]
Tested on Linkedin, but the button styles are not displaying for some reason. Tried on github too. Same problem.

screen shot 2015-02-28 at 11 17 17

**Comment by xarg** [comment]
Sorry I force pushed this branch. It was difficult to merge it with master.

Here are a few comments:

- [ ] Let's only enable the QA button on Gmail Compose Body. It's going to be easier to test and it's the most important location for us right now.
- [ ] I added a tooltip with Gmail style, however the spacing is a bit weird. Should do something about it (perhaps put it on top?)
- [ ] The autofocus on the search dialog is lost. Kind of important that it has focus after you enable it.
- [ ] The position of the QA button keeps changing when I switch between To and Body fields:
screen shot 2015-03-09 at 11 48 50
screen shot 2015-03-09 at 11 48 43
- [ ] The button and dialog styles are misaligned:

screen shot 2015-03-09 at 11 49 23

**Comment by ghinda** [comment]
I finished up most of the remaining work on this. It seems to work on pretty much any website, as far as I've tested (tested on Gmail and Github mostly, but also created some local contenteditable and textarea elements and everything seems ok). 

The pr also fixes a lot of positioning issues with the dialog, and some caret positioning issues in textareas. This is why all the conflicts. I've merged in `master` and resolved them.

The button will show up for any `textarea`, `input[type=text]`, or `contenteditable` that is bigger than 100x100px. So this fixes the issues with it showing up in the `To/From` fields.

I've changed the active style on the button, so that looks better now.
Also fixed the issue with auto-focusing the search field in the dialog.

If you don't find any other bugs, it should be ready for shipping.

**Comment by xarg** [comment]
Nice work. The problem with the positioning is still there however:
giphy

Not sure what is causing this.

**Comment by ghinda** [comment]
I think the issue was caused by the disappearing `From` field, when focusing the mail body. 

I added a `500ms` delay before the quick action button shows up (and calculates its position), so that should fix it.

That gmail tooltip is very smart.

**Pull request merged**
