### PR TITLE
Sorting feature

### LINKED ISSUE #167: Sort templates by alphabetical order
+2

### PR DESCRIPTION
**Pull request by paultrh**
Work on issue (fixes #167)

#### Options

Sort template list
Sort template list in dialog (gmail)

---
This change is [Reviewable](https://reviewable.io/reviews/gorgias/gorgias-chrome/255)

### CODE REVIEW

**Comment by xarg** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/content/js/index.js, line 110 at r1](https://reviewable.io:443/reviews/gorgias/gorgias-chrome/255#-KwzsDHMenH06vgAlwwo:-KwzsDHMenH06vgAlwwp:btvvm5x) ([raw file](https://github.com/gorgias/gorgias-chrome/blob/6288eb5e25ca9df8d456311b3fb36f06db39c283/src/content/js/index.js#L110)):*
> ```JavaScript
> 
>                         // Decide sorting policy
>                         Settings.get('settings', {}, function (settings) {
> ```

we already have the settings in `App.settings.` so there is no need for this promise. You also won't need to duplicate the limit code if you use that.

---

*[src/pages/views/settings.html, line 164 at r1](https://reviewable.io:443/reviews/gorgias/gorgias-chrome/255#-KwzsYl8RULF8mGp7JtR:-KwzsYl8RULF8mGp7JtS:bfxvx9m) ([raw file](https://github.com/gorgias/gorgias-chrome/blob/6288eb5e25ca9df8d456311b3fb36f06db39c283/src/pages/views/settings.html#L164)):*
> ```HTML
>         <label>
>             <input type="checkbox" id="sidebar-enabled" ng-model="settings.is_sort_template_list" ng-change="updateSettings()"/>
>             Sort template List
> ```

Sort templates alphabetically in the Options page.

---

*[src/pages/views/settings.html, line 170 at r1](https://reviewable.io:443/reviews/gorgias/gorgias-chrome/255#-KwzsxS_NxlwkS7my6bw:-KwzsxS_NxlwkS7my6bx:b-u97pcm) ([raw file](https://github.com/gorgias/gorgias-chrome/blob/6288eb5e25ca9df8d456311b3fb36f06db39c283/src/pages/views/settings.html#L170)):*
> ```HTML
>         <label>
>             <input type="checkbox" id="sidebar-enabled" ng-model="settings.is_sort_template_dialog_gmail" ng-change="updateSettings()"/>
>             Sort template Dialog in Gmail™
> ```

Sort templates alphabetically in the Auto-complete Dialog.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gorgias/gorgias-chrome/255)*

**Comment by xarg** [comment]
Please +1 the version in the package.json and manifest.json and add yourself to the contributor list in package.json.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/gorgias/gorgias-chrome/255#-:-KwztF4gIUgOiy4SDZbk:bh2dwzh)*

**Comment by paultrh** [comment]
Review status: 1 of 4 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/content/js/index.js, line 110 at r1](https://reviewable.io:443/reviews/gorgias/gorgias-chrome/255#-KwzsDHMenH06vgAlwwo:-Kx-b7V9W4Quze7YQsFq:b-896fix) ([raw file](https://github.com/gorgias/gorgias-chrome/blob/6288eb5e25ca9df8d456311b3fb36f06db39c283/src/content/js/index.js#L110)):*
<details><summary><i>Previously, xarg (Alex Plugaru) wrote…</i></summary><blockquote>

we already have the settings in `App.settings.` so there is no need for this promise. You also won't need to duplicate the limit code if you use that.
</blockquote></details>

Done.

---

*[src/pages/views/settings.html, line 164 at r1](https://reviewable.io:443/reviews/gorgias/gorgias-chrome/255#-KwzsYl8RULF8mGp7JtR:-Kx-aqmjZG7dGzRSXQT9:b-896fix) ([raw file](https://github.com/gorgias/gorgias-chrome/blob/6288eb5e25ca9df8d456311b3fb36f06db39c283/src/pages/views/settings.html#L164)):*
<details><summary><i>Previously, xarg (Alex Plugaru) wrote…</i></summary><blockquote>

Sort templates alphabetically in the Options page.
</blockquote></details>

Done.

---

*[src/pages/views/settings.html, line 170 at r1](https://reviewable.io:443/reviews/gorgias/gorgias-chrome/255#-KwzsxS_NxlwkS7my6bw:-Kx-b5z7pnxmVrBFgfyW:b-896fix) ([raw file](https://github.com/gorgias/gorgias-chrome/blob/6288eb5e25ca9df8d456311b3fb36f06db39c283/src/pages/views/settings.html#L170)):*
<details><summary><i>Previously, xarg (Alex Plugaru) wrote…</i></summary><blockquote>

Sort templates alphabetically in the Auto-complete Dialog.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gorgias/gorgias-chrome/255)*

**Comment by xarg** [comment]
Nice work @paultrh!

**Pull request closed without merging**
