### PR TITLE
Google Inbox hotfix for inserting templates when editor is empty

### PR DESCRIPTION
**Pull request by ghinda**
#### Connects to #109 

In Google Inbox:
* Fixes issues with inserting templates when the editor is empty:
https://github.com/gorgias/gorgias-chrome/issues/109#issuecomment-282179077
* Enable the quick-action button

#### Question:
* Should I tweak the dialog positioning to consider the element's padding?
dialog-position

---
This change is [Reviewable](https://reviewable.io/reviews/gorgias/gorgias-chrome/246)

### CODE REVIEW

**Comment by xarg** [comment]
Sorry it took so long to reply. I really need to start managing my time better..

No need to tweak the position of the dialog for now.

I noticed 2 issues:

- [ ] BCC field is not updated when used.
- [ ] Template is not filled when replying. I get an error (the template was all optional fields filled):

screen shot 2017-03-23 at 10 34 05 am

**Comment by xarg** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/gorgias/gorgias-chrome/246)*

**Comment by ghinda** [comment]
I couldn't reproduce the exact issues but found two similar ones:
* The BCC was filled with data for the CC field, in Google Inbox
* The entire `from` object was empty in Google Inbox

Can you take a look and see if there are still any issues?

**Comment by xarg** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/gorgias/gorgias-chrome/246)*

**Comment by xarg** [comment]
I can't reproduce any other issues. Nice work :thumbsup: 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/gorgias/gorgias-chrome/246#-:-KgGmRw7d65sC7xkw7AS:bbybuwa)*

**Pull request merged**
