### PR TITLE
webpack integration

### PR DESCRIPTION
**Pull request by thomasgit123**
test function still needs more work, but others are working perfectly.

---
This change is [Reviewable](https://reviewable.io/reviews/gorgias/gorgias-chrome/272)

### CODE REVIEW

**Comment by xarg** [comment]
The content script is breaking my gmail style (seems the body styles are not restricted to gorgias chrome popup anymore):



Please automatically format the files (number of spaces, etc..)

---

Reviewed 14 of 16 files at r1.
Review status: 14 of 16 files reviewed at latest revision, all discussions resolved.

---

*[Gruntfile.js, line 3 at r1](https://beta.reviewable.io/reviews/gorgias/gorgias-chrome/272#-L8ha_ch3u92o3gBnzy4:-L8ha_ch3u92o3gBnzy5:buljir2) ([raw file](https://github.com/gorgias/gorgias-chrome/blob/4392d7969bd72d6640392a46adde5f951d8876ba/Gruntfile.js#L3)):*
> ```JavaScript
> 'use strict';
> 
> module.exports = function (grunt) {
> ```

gruntfile should be deleted no?

---

*[webpack.config.js, line 5 at r1](https://beta.reviewable.io/reviews/gorgias/gorgias-chrome/272#-L8hZYAt3KZu_LA6czAH:-L8hZYAt3KZu_LA6czAI:bhtv61p) ([raw file](https://github.com/gorgias/gorgias-chrome/blob/4392d7969bd72d6640392a46adde5f951d8876ba/webpack.config.js#L5)):*
> ```JavaScript
>     stylus = require("stylus")
>     fileSystem = require("fs"),
>     jshint = require("jshint-loader")
> ```

missing commas here. Also at Gorgias we prefer one declaration per line (it's our convention). Example:

var a = 1;
var b = 2;
etc..

---

*[config/webpack.test.js, line 4 at r1](https://beta.reviewable.io/reviews/gorgias/gorgias-chrome/272#-L8haKud9Ak11O6bcJNc:-L8haKud9Ak11O6bcJNd:b3nq2xz) ([raw file](https://github.com/gorgias/gorgias-chrome/blob/4392d7969bd72d6640392a46adde5f951d8876ba/config/webpack.test.js#L4)):*
> ```JavaScript
> 
> exports.generateCrx = ({}) => {
>     
> ```

please use an editor that understands `.editorconfig` like WebStorm.

---

*[src/manifest.json, line 41 at r1](https://beta.reviewable.io/reviews/gorgias/gorgias-chrome/272#-L8hax720lQkUBirHC5m:-L8hax720lQkUBirHC5n:b-mserfz) ([raw file](https://github.com/gorgias/gorgias-chrome/blob/4392d7969bd72d6640392a46adde5f951d8876ba/src/manifest.json#L41)):*
> ```JSON
>             ],
>             "css": [
>                 "background/css/background.css"
> ```

that's a big no-no. the content.css is specific for the content script part of the extension.

---

*[src/background/css/installed.styl, line 1 at r1](https://beta.reviewable.io/reviews/gorgias/gorgias-chrome/272#-L8haCP3BG3NinpVK_Tl:-L8haCP3BG3NinpVK_Tm:b-qjid6u) ([raw file](https://github.com/gorgias/gorgias-chrome/blob/4392d7969bd72d6640392a46adde5f951d8876ba/src/background/css/installed.styl#L1)):*
> ```Stylus
> @import "../../../node_modules/bootstrap/dist/css/bootstrap.css";
> ```

can you check if `@import "~bootstrap/dist..."` works?

---

*[src/pages/views/installed.html, line 1 at r1](https://beta.reviewable.io/reviews/gorgias/gorgias-chrome/272#-L8ha74JDwtd9HYYUTiA:-L8ha74JDwtd9HYYUTiB:b-etvl56) ([raw file](https://github.com/gorgias/gorgias-chrome/blob/36f8b360d24adbf524d935523e37fa0f2e9e1b34/src/pages/views/installed.html#L1)):*
> ```HTML
> <link href="../background/css/installed.css" rel="stylesheet" type="text/css" media="screen" charset="utf-8">
> ```

are you sure here?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/gorgias/gorgias-chrome/272#-:-L8h_k79-6hUe2X6wOc0:bmbka0z)*

**Comment by xarg** [comment]
Review status: 14 of 18 files reviewed at latest revision, 6 unresolved discussions.

---

*[README.md, line 25 at r2](https://beta.reviewable.io/reviews/gorgias/gorgias-chrome/272#-L8hbBK51FT6rTx0HXn7:-L8hbBK51FT6rTx0HXn8:b9e7h9m) ([raw file](https://github.com/gorgias/gorgias-chrome/blob/e0d6fb6e450a4bd656512ef78de54369e89ff670/README.md#L25)):*
> ```Markdown
> * `yarn start` - Development mode. Creates development manifest, watches for styl files and recompiles them automatically.
> * `yarn build` - Build extension and compress extension.
> * `grunt test` or `grunt t` - Run tests.
> ```

npm test no?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/gorgias/gorgias-chrome/272)*

**Comment by xarg** [comment]
remove bower_components from the repo

---

Reviewed 2 of 16 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/gorgias/gorgias-chrome/272#-:-L8hbYYoEnIbPdpK3o6U:b-t6j444)*

**Comment by thomasgit123** [comment]
currently all style files merged into one file: background.css.

**Comment by xarg** [comment]
Re: background.css - that's not an option since in the content side we have a separate css which is a lot smaller and specific for the content side.

**Comment by thomasgit123** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[Gruntfile.js, line 3 at r1](https://beta.reviewable.io/reviews/gorgias/gorgias-chrome/272#-L8ha_ch3u92o3gBnzy4:-L8hgTMf4tmbxwj-2Cn3:b-x87xdk) ([raw file](https://github.com/gorgias/gorgias-chrome/blob/4392d7969bd72d6640392a46adde5f951d8876ba/Gruntfile.js#L3)):*
<details><summary><i>Previously, xarg (Alex Plugaru) wrote…</i></summary><blockquote>

gruntfile should be deleted no?
</blockquote></details>

grunt will be removed completely after fixing test function with webpack.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/gorgias/gorgias-chrome/272)*

**Comment by thomasgit123** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[README.md, line 25 at r2](https://beta.reviewable.io/reviews/gorgias/gorgias-chrome/272#-L8hbBK51FT6rTx0HXn7:-L8hh5QG8QBz2aGyDfdB:b-jeqe43) ([raw file](https://github.com/gorgias/gorgias-chrome/blob/e0d6fb6e450a4bd656512ef78de54369e89ff670/README.md#L25)):*
<details><summary><i>Previously, xarg (Alex Plugaru) wrote…</i></summary><blockquote>

npm test no?
</blockquote></details>

will write npm test after fixing test with webpack.

---

*[webpack.config.js, line 5 at r1](https://beta.reviewable.io/reviews/gorgias/gorgias-chrome/272#-L8hZYAt3KZu_LA6czAH:-L8hhHFt9D5tYd4O8z-9:b-q8jzb0) ([raw file](https://github.com/gorgias/gorgias-chrome/blob/4392d7969bd72d6640392a46adde5f951d8876ba/webpack.config.js#L5)):*
<details><summary><i>Previously, xarg (Alex Plugaru) wrote…</i></summary><blockquote>

missing commas here. Also at Gorgias we prefer one declaration per line (it's our convention). Example:

var a = 1;
var b = 2;
etc..
</blockquote></details>

got it

---

*[config/webpack.test.js, line 4 at r1](https://beta.reviewable.io/reviews/gorgias/gorgias-chrome/272#-L8haKud9Ak11O6bcJNc:-L8hhM3aAFaklMCx6ZYf:b-w0yspi) ([raw file](https://github.com/gorgias/gorgias-chrome/blob/4392d7969bd72d6640392a46adde5f951d8876ba/config/webpack.test.js#L4)):*
<details><summary><i>Previously, xarg (Alex Plugaru) wrote…</i></summary><blockquote>

please use an editor that understands `.editorconfig` like WebStorm.
</blockquote></details>

got it.

---

*[src/manifest.json, line 41 at r1](https://beta.reviewable.io/reviews/gorgias/gorgias-chrome/272#-L8hax720lQkUBirHC5m:-L8hhRtTCrNHKHXRQrg0:b-hddas) ([raw file](https://github.com/gorgias/gorgias-chrome/blob/4392d7969bd72d6640392a46adde5f951d8876ba/src/manifest.json#L41)):*
<details><summary><i>Previously, xarg (Alex Plugaru) wrote…</i></summary><blockquote>

that's a big no-no. the content.css is specific for the content script part of the extension.
</blockquote></details>

will try to separate them.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/gorgias/gorgias-chrome/272)*

**Comment by xarg** [comment]
Reviewed 743 of 743 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/gorgias/gorgias-chrome/272)*

**Comment by thomasgit123** [comment]
Review status: 748 of 760 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/pages/views/installed.html, line 1 at r1](https://beta.reviewable.io/reviews/gorgias/gorgias-chrome/272#-L8ha74JDwtd9HYYUTiA:-L9HnvHe3EXjwIC2Rsqv:b-bkesfh) ([raw file](https://github.com/gorgias/gorgias-chrome/blob/36f8b360d24adbf524d935523e37fa0f2e9e1b34/src/pages/views/installed.html#L1)):*
<details><summary><i>Previously, xarg (Alex Plugaru) wrote…</i></summary><blockquote>

are you sure here?
</blockquote></details>

it's merged into background.css

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/gorgias/gorgias-chrome/272)*

**Pull request merged**
