### PR TITLE
local export template function integration

### PR DESCRIPTION
**Pull request by thomasgit123**
This change is [Reviewable](https://reviewable.io/reviews/gorgias/gorgias-chrome/273)

### CODE REVIEW

**Comment by xarg** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---

*[src/background/js/controllers/list.js, line 473 at r1](https://beta.reviewable.io/reviews/gorgias/gorgias-chrome/273#-L9R2bMs92SGSuR_O7pJ:-L9R2bMs92SGSuR_O7pK:b-lqhymd) ([raw file](https://github.com/gorgias/gorgias-chrome/blob/30b59b2da4b0dcc6a58e9194037e28efb52f0bf0/src/background/js/controllers/list.js#L473)):*
> ```JavaScript
>             var headers = Object.keys(items[0]);
>             var csv = items.map(function(row){
>                 return headers.map(function(fieldName){
> ```

why not use a CSV package that will do the escape for you? can you find one that is lightweight?

---

*[src/pages/views/list.html, line 17 at r1](https://beta.reviewable.io/reviews/gorgias/gorgias-chrome/273#-L9R1tIW6iXbDL2J_Vqp:-L9R1tIW6iXbDL2J_Vqq:b-1ivw) ([raw file](https://github.com/gorgias/gorgias-chrome/blob/237870940384b7a1a4e0bd9c8ce5626b5b51b427/src/pages/views/list.html#L17)):*
> ```HTML
>              class="btn-group btn-more pull-right">
>             <a class="btn btn-default" href data-toggle="modal" data-target="#import-modal">Import</a>
>             <a class="btn btn-default" href="{{baseUrl}}app/export/templates.csv" target="_blank"
> ```

instead of removing this completely, display the original export link for logged in users and the other export for free users.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/gorgias/gorgias-chrome/273)*

**Comment by thomasgit123** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/background/js/controllers/list.js, line 473 at r1](https://beta.reviewable.io/reviews/gorgias/gorgias-chrome/273#-L9R2bMs92SGSuR_O7pJ:-L9R4ipk7f75WJNzF6Bv:bgbyl31) ([raw file](https://github.com/gorgias/gorgias-chrome/blob/30b59b2da4b0dcc6a58e9194037e28efb52f0bf0/src/background/js/controllers/list.js#L473)):*
<details><summary><i>Previously, xarg (Alex Plugaru) wrote…</i></summary><blockquote>

why not use a CSV package that will do the escape for you? can you find one that is lightweight?
</blockquote></details>

I don't think we need to install new package for this simple function.
thought best light package would be this simple functions... :)
do we need to use package instead of this?

---

*[src/pages/views/list.html, line 17 at r1](https://beta.reviewable.io/reviews/gorgias/gorgias-chrome/273#-L9R1tIW6iXbDL2J_Vqp:-L9R5WjC5pUjFYz_-0xe:b-6k97zo) ([raw file](https://github.com/gorgias/gorgias-chrome/blob/237870940384b7a1a4e0bd9c8ce5626b5b51b427/src/pages/views/list.html#L17)):*
<details><summary><i>Previously, xarg (Alex Plugaru) wrote…</i></summary><blockquote>

instead of removing this completely, display the original export link for logged in users and the other export for free users.
</blockquote></details>

got it. so if users logged in, export function will use backend api, but in othercase , free users will use export function on extension side?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/gorgias/gorgias-chrome/273)*

**Comment by xarg** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/background/js/controllers/list.js, line 473 at r1](https://beta.reviewable.io/reviews/gorgias/gorgias-chrome/273#-L9R2bMs92SGSuR_O7pJ:-L9R6oqg1Xi7J1BjM_t4:b8w98es) ([raw file](https://github.com/gorgias/gorgias-chrome/blob/30b59b2da4b0dcc6a58e9194037e28efb52f0bf0/src/background/js/controllers/list.js#L473)):*
<details><summary><i>Previously, thomasgit123 (Dream Software) wrote…</i></summary><blockquote>

I don't think we need to install new package for this simple function.
thought best light package would be this simple functions... :)
do we need to use package instead of this?
</blockquote></details>

the fact is your function is not really generating a correct CSV file. What happens if you have a comma in the body? do you escape new lines as well? generating a correct CSV is not as easy as it appears.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/gorgias/gorgias-chrome/273)*

**Comment by thomasgit123** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/background/js/controllers/list.js, line 473 at r1](https://beta.reviewable.io/reviews/gorgias/gorgias-chrome/273#-L9R2bMs92SGSuR_O7pJ:-L9R8QFF4WyA4vJdzoMo:b-bgz8sa) ([raw file](https://github.com/gorgias/gorgias-chrome/blob/30b59b2da4b0dcc6a58e9194037e28efb52f0bf0/src/background/js/controllers/list.js#L473)):*
<details><summary><i>Previously, xarg (Alex Plugaru) wrote…</i></summary><blockquote>

the fact is your function is not really generating a correct CSV file. What happens if you have a comma in the body? do you escape new lines as well? generating a correct CSV is not as easy as it appears.
</blockquote></details>

:(, I tested new line and comma as well, it's working perfectly. but if you want, let's use package.
let me know your final decision. :)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/gorgias/gorgias-chrome/273)*

**Pull request merged**
