### PR TITLE
WYSIWYG editor

### PR DESCRIPTION
**Pull request by ghinda**
This implements the new wysiwyg editor using `textAngular`. 

Features:
* Custom editor toolbar with a dropdown to be able to add gorgias template variables.
* Convert the qt body to markdown when saving it.
* Clean up the editor-generated markdown and remove empty dom nodes, before the markdown conversion, to generate cleaner markdown.
* Convert the qt body from markdown to html, when loading it in the editor.
* If adding the qt (with the content script) to a `contentEditable` element, convert the markdown to html before inserting it.

### CODE REVIEW

**Comment by xarg** [comment]
For some reason the newlines in the existing templates have disappeared:

screen shot 2015-02-13 at 11 40 12

However, when I do the completion it's ok, it has the newlines.

**Comment by xarg** [comment]
There is a problem with the newlines when editing a message. You can see the video to understand better what I'm talking about.  

https://www.youtube.com/watch?v=YRyIsOdnDiA

My guess is that it adds a <p> for some reason. Same goes when editing the template in the editor.

**Comment by ghinda** [comment]
Pushed a small fix for this, let me know if it fixes the issue.

**Comment by xarg** [comment]
When a template that contains links or an image and is inserted in a textarea the markdown is not stripped. 

It inserts something like this: ``[link title](http://google.com)`` I guess instead it should probably insert just http://google.com. Do you think it's possible to strip the markdown before insertion in a non-contenteditable?

**Comment by xarg** [comment]
When inserting any template in contenteditable it is surrounded by a `<p>` thus adding top/bottom padding.

**Comment by ghinda** [comment]
I fixed the issues with wrapping lines in `p`'s when adding to contenteditables, by wrapping the inserted template in a `div`. Seems to be the only way to prevent `marked` from adding the `p`s. Also made some other improvements for the editor and markdown handling.

Implemented the feature for replacing markdown images and links with just the plaintext links, when adding templates to non-contenteditables.

I had to merge the master branch into this one, to avoid conflicts with the md image/link replace code.

**Pull request closed without merging**
